# Generated by Django 4.0.3 on 2022-05-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='earnings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='value_to_yoli',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
