# Generated by Django 4.0.3 on 2022-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0005_product_earnings_product_value_to_yoli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='earnings',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_to_yoli',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
